In [1]:
import numpy as np
n0=np.zeros((1,2))
n00= np.zeros((5,5))
n1= np.array([1,2,3,4])
n2=np.array([[1,2,3,4],[10,20,30,40]]) 
nfull= np.full((2,2),10) #--> 2 * 2 matrix with each element being 10
nrange=np.arange(10,20,2) #-> no incremental value here the range is 10 - 19 inclusive of start range and exclusive of end range
nrangelimit=np.arange(10,20,5) #-> no incremental value here the range is 10 - 19

print(n0)
print(n00)
print(n1)
print(n2)
print(nfull)
print(nrange)
print(nrangelimit)

[[0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1 2 3 4]
[[ 1  2  3  4]
 [10 20 30 40]]
[[10 10]
 [10 10]]
[10 12 14 16 18]
[10 15]


In [27]:
n1= np.random.randint(1,100,5) #--> 5 values between 1 -100 random values
print(n1)

n2=np.array([[1,2,3,4],[10,20,30,40]]) 
n2.shape
n2.shape=(4,2)
print(n2)


[59 78 74 87 85]
[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [28]:
# Joining Numpy Arrays
# vstack() --> stack numpy arrays vertically
# hstack() --> Stack numpy arrays horizontally
# column_stack() --> stack numpy arrays column based, values of each array go as an independent column

n1=np.array([1,2,3,4])
n2=np.array([10,20,30,40])
np.vstack((n1,n2))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [29]:
np.hstack((n1,n2))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [30]:
np.column_stack((n1,n2))


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [31]:
n1=np.array([10,20,30,40])
n2=np.array([10,50,50,60,70])
np.intersect1d(n1,n2) #--> common values would be output



array([10])

In [32]:
np.setdiff1d(n1,n2) #--> those elements which are included in n2 array will be excluded and only elements which are present in n1 will be output

array([20, 30, 40])

In [34]:
# Addition of Numpy Array
n1=np.array([1,2,3,4])
n2= np.array([5,6,7,8])
np.sum([n1,n2])

36

In [35]:
np.sum([n1,n2],0) # the second argument is axis, 0 axis means it will add a0 with b0, and a1 with b1

array([ 6,  8, 10, 12])

In [36]:
# the second argument is axis, 1 axis means it will add all 1st array elements and 2nd array elements independently 
np.sum([n1,n2],axis=1) 

array([10, 26])

In [37]:
# if you want to add/multiply/divide/subtract scalar values to array elements

n1=np.array([1,2,3])
n1+1


array([2, 3, 4])

In [38]:
n1*2

array([2, 4, 6])

In [39]:
n1 -1

array([0, 1, 2])

In [41]:
n1 / 2 # n//2

array([0.5, 1. , 1.5])

In [42]:
# Mean, standard deviation, standard

n1= np.array([10,20,30,40])
np.mean(n1)

25.0

In [43]:
np.median(n1)

25.0

In [44]:
np.std(n1) #standard deviation

11.180339887498949

In [46]:
# saving and loading numpy arrays
n1=np.array([10,20,30,40,50])
np.save('my_numpy',n1)
np.load('my_numpy.npy') # when you want to load a saved array you have load using npy extension

array([10, 20, 30, 40, 50])